[sncast.sepolia_fix]
account = "sepolia"
url = "https://starknet-sepolia.g.alchemy.com/starknet/version/rpc/v0_8/PoSTfSa4MmSbEbXRWyHoQ"
fee-token = "strk"
wait-params = { timeout = 500, retry-interval = 10 }
